#! /usr/bin/python
#creating a server that is open for requests

import socket
#If we are using Watson
#need to run: pip install --upgrade "watson-developer-cloud>=2.2.6"
from watson_developer_cloud import TextToSpeechV1

text_to_speech = TextToSpeechV1(
    username='b6ef0754-fe3c-4ff6-973e-5a3d1a284d89',
    password='jB4AR6qxJBjf',
    url='https://stream.watsonplatform.net/text-to-speech/api'
)

def open_server():
    serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    #http?telnet?
    serversocket.bind(('localhost', 80))
    serversocket.listen(5)
  
def recieve_question_data():
    return

def get_answer(quest_text):
    #return funnt answer
    return

def create_mp3_from_text(my_answer_text):
    #return MP3
    #Here is a good expample to how to use Watson API for text2speach:
    #https://www.ibm.com/watson/developercloud/text-to-speech/api/v1/python.html?python#websocket_methods
    #another option is to use API of google
    #https://cloud.google.com/text-to-speech/docs/create-audio#text-to-speech-text-python
    return

def send_mp3_to_client(mp3_file):
    return

def main():
    print "helllooooooooooo"
