#! /usr/bin/python

#creating a server that is open for requests
import socket

def open_server():
  serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  #http?telnet?
  serversocket.bind(('localhost', 80))
  serversocket.listen(5)
  

